# Generated by Django 5.0.6 on 2024-08-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
